CREATE DATABASE CAdb;

use CAdb;

CREATE TABLE cuenta (
	numero INT(10)PRIMARY KEY,
	propietario VARCHAR(30) NOT NULL,
	tipo VARCHAR(10) NOT NULL,
	saldo FLOAT(10) UNSIGNED NOT NULL DEFAULT '0.0'
);
CREATE TABLE transaccion (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	monto FLOAT(10) NOT NULL,
	tipo VARCHAR(50) NOT NULL,
	cedula INT(10) NOT NULL
);
CREATE TABLE familiar (
	cedula INT(10) NOT NULL PRIMARY KEY,
	nombre VARCHAR(20) NOT NULL,
	apellido VARCHAR(20) NOT NULL,
	email VARCHAR(20) NOT NULL,
	parentesco VARCHAR(20) NOT NULL,
	--numero INT(10) NOT NULL
	--FOREIGN KEY (numero) REFERENCES cuenta(numero)
);
CREATE TABLE resenia (
	idres INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	correo VARCHAR(30) NOT NULL,
	mensaje VARCHAR(50) NOT NULL
);
SHOW TABLES;

